import { useState } from 'react';
import { Link } from 'react-router-dom';

// قائمة الأنماط أصبحت أبسط، بدون الـ prompt_suffix السري
const styleOptions = [
  { name: 'Default', value: 'default' },
  { name: 'Cinematic', value: 'cinematic' },
  { name: 'Photographic', value: 'photographic' },
  { name: 'Anime', value: 'anime' },
  { name: 'Digital Art', value: 'digital-art' },
  { name: 'Pixel Art', value: 'pixel-art' },
  { name: 'Fantasy Art', value: 'fantasy-art' },
  { name: 'Neonpunk', value: 'neonpunk' },
  { name: '3D Model', value: '3d-model' },
];

const sizeOptions = [
  { label: 'Square (1024x1024)', value: '1024x1024' },
  { label: 'Widescreen (1024x576)', value: '1024x576' },
  { label: 'Portrait (576x1024)', value: '576x1024' },
];

const faqData = [
    {
      question: 'Is Artigen Pro truly free to use?',
      answer: 'Yes, absolutely. Artigen Pro is 100% free. There are no hidden fees, subscription plans, or usage limits. Our goal is to make high-quality AI art creation accessible to everyone.'
    },
    {
      question: 'Are the images I create completely unique?',
      answer: 'Yes. Every time you click "Generate," even with the exact same prompt, our AI model creates a brand new, unique image. You get a fresh result with every generation.'
    },
    {
      question: 'What AI model powers this tool?',
      answer: 'Artigen Pro is powered by the advanced FLUX model, which is renowned for its ability to understand complex text descriptions and translate them into highly detailed and coherent images.'
    },
  {
    question: `What's the difference between Artigen Pro and Artigen V2?`,
    answer: (
        <>
            While both models deliver stunning creative results, they each have unique strengths. <strong>Artigen Pro</strong> excels at generating all styles with high precision, from realistic photos to complex artistic designs. 
            <Link to="/artigenv2" className="text-purple-400 hover:underline">Artigen V2</Link>, on the other hand, specializes in producing images with a unique and highly artistic aesthetic, making it the ideal choice for users looking for a distinct artistic touch.
        </>
    )
  },
    {
      question: 'Can I use the generated images for my projects?',
      answer: 'Images generated by this tool are released under a Creative Commons (CC0) license, meaning they are in the public domain. You are free to use them for personal and commercial projects without attribution.'
    },
];


function ImageGeneratorPage() {
  const [prompt, setPrompt] = useState('');
  const [selectedStyle, setSelectedStyle] = useState('default');
  const [selectedSize, setSelectedSize] = useState('1024x1024');
  const [imageUrl, setImageUrl] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleGenerateClick = async () => {
    const userPrompt = prompt.trim();
    if (!userPrompt) {
      setError('Please enter a description for the image.');
      return;
    }

    setIsLoading(true);
    setError(null);
    setImageUrl('');
    
    try {
        const response = await fetch('/api/image-generators?tool=image-pro', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                userPrompt: userPrompt,
                style: selectedStyle,
                size: selectedSize,
            }),
        });

        const data = await response.json();

        if (!response.ok) {
            throw new Error(data.error || 'Failed to generate image.');
        }

        const generatedUrl = data.imageUrl;
        
        const img = new Image();
        img.src = generatedUrl;

        img.onload = () => {
            setImageUrl(generatedUrl);
            setIsLoading(false);
        };

        img.onerror = () => {
            setError('Failed to load the image. The AI service may be busy. Please try again later.');
            setIsLoading(false);
        };
    } catch (err: any) {
        setError(err.message);
        setIsLoading(false);
    }
  };
  
  const handleDownloadClick = async () => {
      if (!imageUrl) return;
      try {
        const response = await fetch(imageUrl);
        const blob = await response.blob();
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.style.display = 'none';
        a.href = url;
        const filename = `${prompt.substring(0, 20).replace(/\s/g, '_') || 'generated'}_image.png`;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
        document.body.removeChild(a);
      } catch (err) {
        setError('Download failed. You can try right-clicking the image and selecting "Save Image As".');
      }
  };

  return (
    <>
      <title>Artigen Pro: Free AI Image Generator From Text</title>
      <meta name="description" content="Generate stunning, unique images from text prompts with Artigen Pro. Our free AI image generator brings your ideas to life instantly. No sign-up required." />
      <link rel="canonical" href="https://aiconvert.online/generate-image-pro" />
      <link rel="alternate" hrefLang="en" href="https://aiconvert.online/generate-image-pro" />
      <link rel="alternate" hrefLang="ar" href="https://aiconvert.online/ar/generate-image-pro" />
      <link rel="alternate" hrefLang="x-default" href="https://aiconvert.online/generate-image-pro" />
      <script type="application/ld+json">
        {`
          {
            "@context": "https://schema.org",
            "@type": "SoftwareApplication",
            "name": "Artigen Pro AI Image Generator",
            "operatingSystem": "WEB",
            "applicationCategory": "MultimediaApplication",
            "aggregateRating": {
              "@type": "AggregateRating",
              "ratingValue": "4.8",
              "ratingCount": "1250"
            },
            "offers": {
              "@type": "Offer",
              "price": "0",
              "priceCurrency": "USD"
            }
          }
        `}
      </script>
      
      <div className="pt-24 bg-gray-900 text-white min-h-screen">
        <main className="max-w-7xl mx-auto p-4 sm:p-6 lg:p-8">
          <div className="text-center mb-12">
            <h1 className="text-4xl sm:text-5xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-600">
              Artigen Pro AI Image Generator
            </h1>
            <p className="mt-4 text-lg text-gray-300 max-w-2xl mx-auto">
              Bring your ideas to life. Describe anything you can imagine, select a style, and watch our free text to image AI create a unique masterpiece for you.
            </p>
          </div>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 lg:gap-12">
            <div className="bg-gray-800 p-6 rounded-2xl shadow-lg flex flex-col gap-6">
              <div>
                <label htmlFor="prompt-input" className="block text-sm font-medium text-gray-300 mb-2">1. Describe your image</label>
                <textarea
                  id="prompt-input"
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  placeholder="e.g., A cute cat astronaut floating in space"
                  className="w-full h-24 p-3 bg-gray-700 border border-gray-600 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-purple-500 transition"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">2. Choose a style</label>
                <div className="grid grid-cols-3 sm:grid-cols-4 gap-2">
                  {styleOptions.map((style) => (
                    <button
                      key={style.value}
                      onClick={() => setSelectedStyle(style.value)}
                      className={`p-2 text-center text-sm rounded-lg transition-all duration-200 ${
                        selectedStyle === style.value ? 'bg-purple-600 text-white font-bold ring-2 ring-purple-400' : 'bg-gray-700 hover:bg-gray-600'
                      }`}
                    >
                      {style.name}
                    </button>
                  ))}
                </div>
              </div>
              <div>
                <label htmlFor="size-select" className="block text-sm font-medium text-gray-300 mb-2">3. Select image size</label>
                <select
                  id="size-select"
                  value={selectedSize}
                  onChange={(e) => setSelectedSize(e.target.value)}
                  className="w-full p-3 bg-gray-700 border border-gray-600 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-purple-500"
                >
                  {sizeOptions.map(size => (<option key={size.value} value={size.value}>{size.label}</option>))}
                </select>
              </div>
              <button
                onClick={handleGenerateClick}
                disabled={isLoading}
                className="w-full mt-2 py-3 px-4 text-lg font-bold text-white bg-gradient-to-r from-purple-600 to-pink-600 rounded-lg hover:from-purple-700 hover:to-pink-700 focus:outline-none focus:ring-4 focus:ring-purple-300 disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-300"
              >
                {isLoading ? 'Generating...' : 'Generate Image'}
              </button>
              {error && <p className="text-red-400 text-center mt-2">{error}</p>}
            </div>
            <div className="bg-gray-800 p-6 rounded-2xl shadow-lg flex flex-col justify-center items-center h-96 lg:h-auto">
              <div className="w-full h-full flex justify-center items-center border-2 border-dashed border-gray-600 rounded-lg">
                {isLoading && (<div className="flex flex-col items-center gap-4"><div className="animate-spin rounded-full h-16 w-16 border-t-4 border-b-4 border-purple-500"></div><p className="text-gray-400">Creating your vision...</p></div>)}
                {!isLoading && !imageUrl && (<div className="text-center text-gray-400"><p>Your generated image will appear here</p></div>)}
                {imageUrl && !isLoading && (<img src={imageUrl} alt={prompt} className="max-w-full max-h-full object-contain rounded-lg" />)}
              </div>
              {imageUrl && !isLoading && (<button onClick={handleDownloadClick} className="w-full mt-6 py-3 px-4 text-lg font-bold text-white bg-green-600 rounded-lg hover:bg-green-700 focus:outline-none focus:ring-4 focus:ring-green-300 transition-all duration-300">Download Image</button>)}
            </div>
          </div>
          <div className="mt-24">
              <section className="text-center">
                  <h2 className="text-3xl font-bold mb-4">Why is Artigen Pro Your Go-To AI Art Creator?</h2>
                  <p className="max-w-3xl mx-auto text-gray-400 mb-12">In a world of complex tools, Artigen Pro offers a straightforward and powerful experience. We believe creativity should be effortless and accessible to all.</p>
                  <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">
                      <div className="bg-gray-800 p-6 rounded-lg shadow-md">
                          <h3 className="text-xl font-bold text-purple-400 mb-2">Completely Free</h3>
                          <p className="text-gray-300">No subscriptions, no credit cards, no hidden costs. Enjoy unlimited AI image generation on us.</p>
                      </div>
                      <div className="bg-gray-800 p-6 rounded-lg shadow-md">
                          <h3 className="text-xl font-bold text-purple-400 mb-2">No Sign-Up Needed</h3>
                          <p className="text-gray-300">We respect your privacy and time. Jump right into creating without the hassle of registration.</p>
                      </div>
                      <div className="bg-gray-800 p-6 rounded-lg shadow-md">
                          <h3 className="text-xl font-bold text-purple-400 mb-2">Limitless Creation</h3>
                          <p className="text-gray-300">There are no caps on how many images you can generate or download. Your imagination is the only limit.</p>
                      </div>
                      <div className="bg-gray-800 p-6 rounded-lg shadow-md">
                          <h3 className="text-xl font-bold text-purple-400 mb-2">Multi-Language Magic</h3>
                          <p className="text-gray-300">Describe your vision in Arabic, English, or any other language, and our AI will understand and deliver.</p>
                      </div>
                  </div>
              </section>
              <section className="mt-20 text-center">
                   <h2 className="text-3xl font-bold mb-4">Turn Your Ideas into Art in 3 Simple Steps</h2>
                   <p className="max-w-3xl mx-auto text-gray-400 mb-12">Our intuitive process makes AI art creation a breeze for everyone, from beginners to professionals.</p>
                   <div className="grid grid-cols-1 md:grid-cols-3 gap-8 text-left">
                       <div className="bg-gray-800/50 p-6 rounded-lg">
                          <p className="text-purple-400 font-bold text-lg mb-2">Step 1: Describe Your Vision</p>
                          <p className="text-gray-300">Write down what you want to see. Be specific for best results! Instead of "a dog," try "a happy golden retriever puppy playing in a field of sunflowers at sunset."</p>
                       </div>
                        <div className="bg-gray-800/50 p-6 rounded-lg">
                          <p className="text-purple-400 font-bold text-lg mb-2">Step 2: Pick a Style & Size</p>
                          <p className="text-gray-300">Choose an artistic style that matches your idea—from cinematic to anime. Then, select the perfect dimensions for your creation.</p>
                       </div>
                        <div className="bg-gray-800/50 p-6 rounded-lg">
                          <p className="text-purple-400 font-bold text-lg mb-2">Step 3: Generate & Download</p>
                          <p className="text-gray-300">Hit the "Generate" button to witness the AI magic. In moments, your unique image will be ready to download and share with the world.</p>
                       </div>
                   </div>
              </section>
              <section className="mt-20 max-w-4xl mx-auto">
                  <h2 className="text-3xl font-bold text-center mb-10">Frequently Asked Questions</h2>
                  <div className="space-y-6">
                      {faqData.map((faq, index) => (
                          <div key={index} className="bg-gray-800 p-6 rounded-lg">
                              <h3 className="font-bold text-lg text-purple-400 mb-2">{faq.question}</h3>
                              <p className="text-gray-300 leading-relaxed">{faq.answer}</p>
                          </div>
                      ))}
                  </div>
              </section>
          </div>
        </main>
      </div>
    </>
  );
}

export default ImageGeneratorPage;
