// الملف: PrivacyPolicyPage.tsx
import { Link } from 'react-router-dom'; // Or your router's Link component

export default function PrivacyPolicyPage() {
  return (
    <>
      <title>Privacy Policy - AIConvert</title>
      <meta name="description" content="Read the Privacy Policy for AIConvert to understand how we handle your data. We prioritize your privacy and do not store your content." />
      <link rel="canonical" href="https://aiconvert.online/privacy-policy" />
      
      <div className="bg-gray-900 text-gray-300 pt-32 pb-20">
        <main className="max-w-4xl mx-auto px-6 lg:px-8">
          <div className="text-center mb-12">
            <h1 className="text-4xl sm:text-5xl font-extrabold text-white">
              Privacy Policy
            </h1>
            <p className="mt-4 text-lg text-gray-400">
              Last updated: August 06, 2025
            </p>
          </div>

          <div className="space-y-8 text-lg leading-relaxed">
            <p>This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
            <p>By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>

            <section>
              <h2 className="text-3xl font-bold text-white mb-4">1. Interpretation and Definitions</h2>
              <p>For the purposes of this Privacy Policy, capitalized words have the meanings defined below. These definitions apply whether they appear in singular or plural form.</p>
              <ul className="list-disc list-inside space-y-4 mt-4">
                <li><strong>Company</strong> (referred to as "We", "Us", "Our") refers to AIConvert.</li>
                <li><strong>Service</strong> refers to the Website and all the tools available on it.</li>
                <li><strong>Website</strong> refers to AIConvert, accessible from <a href="https://aiconvert.online/" target="_blank" rel="noopener noreferrer" className="text-cyan-400 hover:underline">https://aiconvert.online/</a>.</li>
                <li><strong>You</strong> means the individual accessing or using our Service.</li>
                <li><strong>Device</strong> means any device that can access the Service, such as a computer, a cellphone, or a digital tablet.</li>
                <li><strong>User Content</strong> refers to the images, text, and any other data You upload or submit to our tools for processing.</li>
                <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, which tools are used most often).</li>
              </ul>
            </section>
            
            <section>
              <h2 className="text-3xl font-bold text-white mb-4">2. Data We Do NOT Collect</h2>
              <p>Our philosophy is to provide powerful AI tools with maximum privacy. We have intentionally designed our Service to avoid collecting personal identifiable information. We do **not** require you to create an account, register, or provide personal details like your name or email address to use our tools.</p>
            </section>

            <section>
              <h2 className="text-3xl font-bold text-white mb-4">3. Handling of Your User Content</h2>
              <p>Your privacy is our top priority. Here is our commitment regarding the images and text you process with our tools:</p>
              <ul className="list-disc list-inside space-y-4 mt-4">
                <li><strong>Processing Only:</strong> Your User Content is used solely for the purpose of running the AI model to provide you with the requested service (e.g., restoring a photo, generating a story).</li>
                <li><strong>No Storage:</strong> We do not save, store, or archive your User Content on our servers after the processing is complete. The content is processed in-memory and discarded immediately.</li>
                <li><strong>No Training:</strong> We will **never** use your User Content to train our own AI models or any third-party models. Your creative work remains yours alone.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-3xl font-bold text-white mb-4">4. Usage Data and Analytics</h2>
              <p>We automatically collect a limited amount of anonymous Usage Data to help us understand how our Service is used and to improve it. This may include information such as Your Device's IP address (anonymized), browser type, the pages of our Service that You visit, the time and date of Your visit, and other diagnostic data. This data is aggregated and cannot be used to identify you personally.</p>
            </section>
            
            <section>
              <h2 className="text-3xl font-bold text-white mb-4">5. Cookies and Advertising (Google AdSense)</h2>
              <p>We use Cookies to enhance your experience and to serve advertisements that help keep our services free.</p>
               <ul className="list-disc list-inside space-y-4 mt-4">
                  <li>Third-party vendors, including Google, use cookies to serve ads based on a user's prior visits to our website or other websites.</li>
                  <li>Google's use of advertising cookies enables it and its partners to serve ads to our users based on their visit to our site and/or other sites on the Internet.</li>
                  <li>Users may opt out of personalized advertising by visiting <a href="https://www.google.com/settings/ads" target="_blank" rel="noopener noreferrer" className="text-cyan-400 hover:underline">Google's Ads Settings</a>. Alternatively, you can opt out of a third-party vendor's use of cookies for personalized advertising by visiting <a href="http://www.aboutads.info/choices/" target="_blank" rel="noopener noreferrer" className="text-cyan-400 hover:underline">www.aboutads.info/choices</a>.</li>
              </ul>
               <p className="mt-4">If you have not opted out of third-party ad serving, the cookies of other third-party vendors or ad networks may also be used to serve ads on our site.</p>
            </section>
            
            <section>
              <h2 className="text-3xl font-bold text-white mb-4">6. Security of Your Data</h2>
              <p>We implement reasonable security measures to protect the information we handle. However, please remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While We strive to protect your data, We cannot guarantee its absolute security.</p>
            </section>

            <section>
              <h2 className="text-3xl font-bold text-white mb-4">7. Children's Privacy</h2>
              <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with any data, please contact Us. We will take steps to resolve the issue.</p>
            </section>

            <section>
              <h2 className="text-3xl font-bold text-white mb-4">8. Links to Other Websites</h2>
              <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third-party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.</p>
            </section>

            <section>
              <h2 className="text-3xl font-bold text-white mb-4">9. Changes to this Privacy Policy</h2>
              <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
            </section>

            <section>
              <h2 className="text-3xl font-bold text-white mb-4">10. Contact Us</h2>
              <p>If you have any questions about this Privacy Policy, you can contact us by visiting the <Link to="/contact" className="text-cyan-400 hover:underline">Contact Us</Link> page on our website.</p>
            </section>

          </div>
        </main>
      </div>
    </>
  );
}
