// الملف: TermsOfServicePage.tsx

export default function TermsOfServicePage() {
  return (
    <>
      <title>Terms of Service - AIConvert</title>
      <meta name="description" content="Read the Terms of Service for AIConvert. By using our services, you agree to these terms." />
      <link rel="canonical" href="https://aiconvert.online/terms-of-service" />
      
      <div className="bg-gray-900 text-gray-300 pt-32 pb-20">
        <main className="max-w-4xl mx-auto px-6 lg:px-8">
          <div className="text-center mb-12">
            <h1 className="text-4xl sm:text-5xl font-extrabold text-white">
              Terms of Service
            </h1>
            <p className="mt-4 text-lg text-gray-400">
              Last updated: August 06, 2025
            </p>
          </div>

          <div className="space-y-8 text-lg leading-relaxed">
            <section>
              <h2 className="text-3xl font-bold text-white mb-4">1. Acceptance of Terms</h2>
              <p>Welcome to AIConvert ("Company", "We", "Us", "Our"). By accessing or using our website, <a href="https://aiconvert.online" target="_blank" rel="noopener noreferrer" className="text-cyan-400 hover:underline">aiconvert.online</a>, and its related services (collectively, the "Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use our Service.</p>
            </section>

            <section>
              <h2 className="text-3xl font-bold text-white mb-4">2. Description of Service</h2>
              <p>AIConvert provides a suite of free-to-use, artificial intelligence-powered tools that allow users to process, create, and modify content, such as images and text ("User Content"). The Service is accessible directly through our website without the need for an account or registration.</p>
            </section>

            <section>
              <h2 className="text-3xl font-bold text-white mb-4">3. User Content and Intellectual Property</h2>
              <p>This section outlines the ownership and responsibilities related to content processed through our Service.</p>
              <ul className="list-disc list-inside space-y-4 mt-4">
                <li><strong>Your Responsibility for Your Content:</strong> You are solely responsible for the User Content you upload or submit. You represent and warrant that you own or have the necessary rights, licenses, and permissions to use and submit your User Content. You agree not to submit any content that infringes on any third-party rights.</li>
                <li><strong>Ownership of Generated Content:</strong> You retain full ownership rights to the new content ("Output") generated by our AI tools from your User Content. We claim no ownership over the Output.</li>
                <li><strong>Our Limited License to Your Content:</strong> By submitting User Content to the Service, you grant AIConvert a worldwide, non-exclusive, royalty-free, temporary license to use, reproduce, modify, and process your User Content solely for the purpose of operating the Service and providing the requested Output to you. This license terminates automatically once your request is completed and the Output is delivered.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-3xl font-bold text-white mb-4">4. Acceptable Use Policy</h2>
              <p>You agree not to use the Service to create, upload, or share any content that:</p>
              <ul className="list-disc list-inside space-y-4 mt-4">
                <li>Is illegal, harmful, hateful, defamatory, obscene, or infringing on the rights of others.</li>
                <li>Violates any intellectual property rights, including copyrights and trademarks.</li>
                <li>Contains viruses, malware, or any other malicious code.</li>
                <li>Attempts to reverse-engineer, decompile, or gain unauthorized access to our Service or its underlying technology.</li>
              </ul>
              <p className="mt-4">We reserve the right to investigate and take appropriate action, including refusing service or blocking access, against anyone who, in our sole discretion, violates this provision.</p>
            </section>

            <section>
              <h2 className="text-3xl font-bold text-white mb-4">5. Disclaimers and Warranties</h2>
              <p>The Service is provided on an **"AS IS"** and **"AS AVAILABLE"** basis. To the fullest extent permitted by law, we disclaim all warranties, express or implied, in connection with the Service and your use thereof.</p>
              <p className="mt-4">We do not warrant that the Service will be error-free, uninterrupted, or that the Output generated by the AI will be accurate, reliable, or fit for any particular purpose. You use the Service at your own risk.</p>
            </section>

            <section>
              <h2 className="text-3xl font-bold text-white mb-4">6. Limitation of Liability</h2>
              <p>To the fullest extent permitted by law, in no event will AIConvert, its owners, or affiliates be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to, loss of profits, data, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use, or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence), or any other legal theory, whether or not we have been informed of the possibility of such damage.</p>
            </section>

            <section>
              <h2 className="text-3xl font-bold text-white mb-4">7. Modification and Termination of Service</h2>
              <p>We are constantly changing and improving our Service. We reserve the right to add, alter, or remove functionalities or features, and we may suspend or stop a part of the Service or the entire Service altogether at any time, without prior notice. You acknowledge and agree that we shall not be liable to you or any third party for any modification, suspension, or discontinuance of the Service.</p>
            </section>

            <section>
              <h2 className="text-3xl font-bold text-white mb-4">8. Governing Law</h2>
              <p>These Terms shall be governed and construed in accordance with the laws of Egypt, without regard to its conflict of law provisions. Any disputes arising from these Terms or your use of the Service will be subject to the exclusive jurisdiction of the courts located in Egypt.</p>
            </section>
            
            <section>
              <h2 className="text-3xl font-bold text-white mb-4">9. Contact Us</h2>
              <p>
                If you have any questions about these Terms of Service, you can contact us by email at: 
                <a href="mailto:info@aiconvert.online" className="text-cyan-400 hover:underline ml-2">
                  info@aiconvert.online
                </a>
              </p>
            </section>

          </div>
        </main>
      </div>
    </>
  );
}
