// src/react-app/components/AITools.tsx

import {
Image, Scissors, Volume2, Sparkles, MessageSquare, Wand, ArrowRight, Zap, Wand2,
Pencil, Palette, SprayCan, Drama, Smile, Film, Paintbrush
} from 'lucide-react';
import { Link } from 'react-router-dom';
import VercelImage from './VercelImage'; 

// The tools array with corrected English alt text
const tools = [
  {
    id: 'artigenv2',
    title: 'Artigen V2: AI Art Generator',
    description: 'An AI artist that transforms your text into unique, high-quality artwork with a distinct aesthetic.',
    icon: Palette,
    color: 'from-yellow-500 to-orange-600',
    features: ['Distinct Artistic Style', 'High-Quality Results', 'Completely Free'],
    image: '/images/artigenv2-ai-image-generator.webp',
    alt: 'Promotional image for Artigen V2 AI art generator with a colorful artistic background.'
  },
  {
    id: 'generate-image-pro',
    title: 'Artigen Pro: AI Image Generation',
    description: 'Create stunning, high-quality images from simple text descriptions using our advanced AI models.',
    icon: Image,
    color: 'from-purple-500 to-purple-600',
    features: ['Multiple styles', 'High resolution', 'Commercial use'],
    image: '/images/artigen-pro-ai-image-creator.webp',
    alt: 'Image for Artigen Pro tool with a cosmic nebula background, symbolizing creative possibilities.'
  },
  {
    id: 'anime-ai',
    title: 'AI Anime Generator',
    description: 'Create original anime characters and illustrations in various styles like Modern, 90s Retro, Chibi, and more.',
    icon: SprayCan,
    color: 'from-pink-500 to-orange-600',
    features: ['Multiple Styles', 'OC Creation', 'Free & Unlimited'],
    image: '/images/ai-anime-generation.jpg',
    alt: 'A collage of diverse anime characters generated by the AI anime generator tool.'
  },
  {
    id: 'line-drawing',
    title: 'LineArtify: Photo to Line Drawing',
    description: 'Transform your photos into elegant, clean line art with our AI-powered sketch converter.',
    icon: Pencil,
    color: 'from-cyan-500 to-blue-600',
    features: ['Instant conversion', 'High-quality sketch', 'For artists & creators'],
    image: '/images/image-to-line-drawing-ai.webp',
    alt: 'Example of the photo to line drawing tool, showing a before-and-after conversion.'
  },
  {
    id: 'ai-video-prompt-generator',
    title: 'AI Video Prompt Generator',
    description: 'Turn any static image into a cinematic video prompt. Our AI writes professional scene descriptions for tools like Sora, Veo, and Runway.',
    icon: Film,
    color: 'from-rose-500 to-teal-600',
    features: ['Cinematic Descriptions', 'For Sora, Veo & More', 'Free & No Sign-up'],
    image: '/images/ai-video-prompt-generation.jpg',
    alt: 'Cinematic 3D typography for the "AI Video Prompt Generator" tool.'
  },
  {
    id: "prompt-generator",
    title: "Promptigen: Image to Prompt",
    description: "Reverse-engineer any image into a detailed, creative text prompt for AI art generators like Midjourney.",
    icon: Pencil,
    color: "from-sky-500 to-violet-600",
    features: ["Reverse Engineer Images", "Expert-Level Prompts", "Free & Unlimited"],
    image: "/images/promptigen-image-to-prompt.webp",
    alt: "Promotional image for the Promptigen tool that transforms images into art prompts."
  },
  {
    id: 'remove-background',
    title: 'Background Removal',
    description: 'Remove backgrounds from any image instantly with precision AI that handles complex edges perfectly.',
    icon: Scissors,
    color: 'from-blue-500 to-blue-600',
    features: ['Instant processing', 'Edge detection', 'Custom Backgrounds'],
    image: '/images/remove-images-background.webp',
    alt: 'A before-and-after example of the background removal tool, showing a clean cutout.'
  },
  {
    id: 'text-to-speech',
    title: 'Text to Audio',
    description: 'Convert any text into natural-sounding speech with multiple voices and languages available.',
    icon: Volume2,
    color: 'from-green-500 to-green-600',
    features: ['Natural voices', '138+ languages', 'Custom speed'],
    image: '/images/free-ai-text-to-speech.jpg',
    alt: 'Feature image for the text-to-speech tool with a digital technology background.'
  },
  {
    id: 'ai-face-merge',
    title: 'Mergify: AI Face Swap',
    description: 'Swap faces in any photo with surprising realism. Create fun and creative images by merging faces instantly with our advanced AI face swapper.',
    icon: Drama,
    color: 'from-purple-500 to-fuchsia-600',
    features: ['Realistic AI Swaps', 'Group Photo Support', 'Privacy Focused'],
    image: '/images/mergify-face-swap.jpg',
    alt: 'Demonstration of the AI face merge tool, showing a face blended into various artistic images.'
  },
  {
  id: 'llama-4',
  title: 'Llama-4: Advanced AI Chat',
  description: 'Engage in intelligent conversations with a next-gen AI assistant. Features a vast context memory, chat history, and advanced reasoning capabilities.',
  icon: MessageSquare, 
  color: 'from-emerald-500 to-amber-600',
  features: ['Vast Context Memory', 'Lightning-Fast Speed', 'Export Chat'],
  image: '/images/free-llama-4-ai-chatbot.jpg',
  alt: 'The title "Llama 4: Free Unlimited" in bold, 3D chrome text floating in front of a dynamic, futuristic explosion of light and particles.'
  },
  {
    id: 'cartoonify',
    title: 'Cartoonify Yourself',
    description: 'Instantly turn your photo into a fun, 2D-style cartoon with a single click. Perfect for profile pictures and social media!',
    icon: Smile,
    color: 'from-rose-400 to-purple-600',
    features: ['Instant Conversion', 'Classic 2D Style', 'Free & Simple'],
    image: '/images/cartoonify-yourself.webp',
    alt: 'A before-and-after image of a woman being transformed into a cartoon by the Cartoonify tool.'
  },
  {
    id: 'cartoony-art',
    title: 'DigiCartoony: Photo to Digital Art',
    description: 'Elevate your photos into high-quality digital paintings with a unique, artistic style and detailed rendering.',
    icon: Paintbrush,
    color: 'from-teal-500 to-cyan-600',
    features: ['Digital Painting Style', 'Face Detection', 'High-Quality Art'],
    image: '/images/digicartoony-digital-art.webp',
    alt: 'An example of the DigiCartoony tool transforming a man\'s portrait into digital art.'
  },
  {
    id: "ai-story-generator",
    title: "Storygen: AI Story Generator",
    description: "Unleash your creativity. Turn any picture into a unique, narrative-driven story with our advanced AI.",
    icon: Pencil,
    color: "from-indigo-500 to-violet-600",
    features: ["Deep Narrative AI", "Multi-Lingual Writer", "Instant Inspiration"],
    image: "/images/ai-image-to-story-generator.jpg",
    alt: "A fantasy image for the Storygen tool, showing a story emerging from an open book."
  },
  {
  id: 'ai-photo-colorizer',
  title: 'ColorifyPro: AI Photo Colorizer',
  description: 'Automatically add realistic color to black and white, sepia, or vintage photos, bringing your old memories back to life.',
  icon: Image, // استبدل هذا بالأيقونة المناسبة من مكتبة الأيقونات لديك
  color: 'from-red-500 to-green-600',
  features: ['Colorize Old Photos', 'Realistic & Natural Colors', 'Bring Memories to Life'],
  image: '/images/ai-photo-colorizer-before-after.webp',
  alt: 'A before-and-after comparison from the AI photo colorizer tool, showing a vintage black and white portrait being transformed into a full-color image.'
  },
  {
    id: 'ai-image-enhancer',
    title: 'Image Enhancement',
    description: 'Upscale and enhance your images with AI. Increase resolution while maintaining quality.',
    icon: Sparkles,
    color: 'from-orange-500 to-orange-600',
    features: ['4x upscaling', 'Noise reduction', 'Quality boost'],
    image: '/images/ai-image-enhancement.webp',
    alt: 'A before-and-after example of the image enhancement tool improving facial details.'
  },
  {
    id: 'restore-and-repair-old-photos',
    title: 'PhotoRevive: AI Photo Restoration',
    description: 'Breathe new life into your memories. Our AI automatically repairs old, damaged, and faded photos, removing scratches and enhancing quality.',
    icon: Wand,
    color: 'from-amber-500 to-cyan-600',
    features: ['Remove Scratches', 'Enhance Quality', 'Free & Secure'],
    image: '/images/photorevive-ai-photo-restoration.webp',
    alt: 'A before-and-after example of the PhotoRevive tool repairing an old, damaged photograph.'
  }
];

export default function AITools() {
  return (
    <section id="tools" className="py-20 lg:py-28 bg-white">
      <div className="max-w-7xl mx-auto px-6 lg:px-8">
        <div className="text-center mb-16">
          <div className="inline-flex items-center space-x-2 bg-gradient-to-r from-purple-100 to-blue-100 rounded-full px-4 py-2 mb-6">
            <Wand2 className="h-4 w-4 text-purple-600" />
            <span className="text-sm font-medium text-purple-900">AI-Powered Tools</span>
          </div>
          <h2 className="text-4xl lg:text-5xl font-bold text-gray-900 mb-6">
            Everything You Need to{' '}
            <span className="bg-gradient-to-r from-purple-600 to-blue-600 bg-clip-text text-transparent">
              Create Amazing Content
            </span>
          </h2>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            Our comprehensive suite of AI tools empowers creators, designers, and businesses
            to produce professional-quality content in seconds.
          </p>
        </div>
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 lg:gap-12">
          {tools.map((tool) => (
            <div
              key={tool.id}
              className="group relative bg-white rounded-2xl border border-gray-200 hover:border-gray-300 transition-all duration-300 overflow-hidden hover:shadow-2xl"
            >
              <div className="relative h-48 lg:h-56 overflow-hidden">
                <VercelImage
  src={tool.image}
  alt={tool.alt}
  sizes="(max-width: 1023px) calc(100vw - 3rem), calc(50vw - 4rem)"
  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
/>
                <div className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent"></div>
                <div className={`absolute top-4 left-4 p-3 rounded-xl bg-gradient-to-r ${tool.color} shadow-lg`}>
                  <tool.icon className="h-6 w-6 text-white" />
                </div>
              </div>
              <div className="p-8">
                <h3 className="text-2xl font-bold text-gray-900 mb-3 group-hover:text-purple-600 transition-colors">
                  {tool.title}
                </h3>
                <p className="text-gray-600 mb-6 leading-relaxed">
                  {tool.description}
                </p>
                <div className="flex flex-wrap gap-2 mb-6">
                  {tool.features.map((feature) => (
                    <span
                      key={feature}
                      className="px-3 py-1 text-sm font-medium text-purple-700 bg-purple-100 rounded-full"
                    >
                      {feature}
                    </span>
                  ))}
                </div>
                <Link to={`/${tool.id}`} className="group/btn flex items-center space-x-2 text-purple-600 hover:text-purple-700 font-semibold transition-colors">
                  <span>Try {tool.title}</span>
                  <ArrowRight className="h-4 w-4 group-hover/btn:translate-x-1 transition-transform" />
                </Link>
              </div>
              <div className="absolute inset-0 bg-gradient-to-br from-purple-600/0 to-blue-600/0 group-hover:from-purple-600/5 group-hover:to-blue-600/5 transition-all duration-300 pointer-events-none"></div>
            </div>
          ))}
        </div>
        <div className="text-center mt-16">
          <button className="group inline-flex items-center space-x-2 px-8 py-4 text-lg font-semibold text-white bg-gradient-to-r from-purple-600 to-blue-600 rounded-xl hover:from-purple-700 hover:to-blue-700 transition-all duration-300 shadow-xl hover:shadow-2xl transform hover:scale-105">
            <Zap className="h-5 w-5" />
            <span>Access All Tools Now</span>
            <ArrowRight className="h-5 w-5 group-hover:translate-x-1 transition-transform" />
          </button>
        </div>
      </div>
    </section>
  );
}
